CREATE DATABASE AGENDABD2002;

CREATE TABLE AGENDABD2002.CONTATO (
  ID              INT          NOT NULL AUTO_INCREMENT,
  NOME            VARCHAR(100) NOT NULL,
  APELIDO         VARCHAR(100),
  DATA_NASCIMENTO DATE,
  EMAIL           VARCHAR(100),
  TELEFONE        VARCHAR(20),
  CONSTRAINT PK_CONTATO PRIMARY KEY (ID)
);