
-- MySQL Script generated by MySQL Workbench
-- Thu Oct 22 09:53:44 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema semAglomerar
-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS `semAglomerar` DEFAULT CHARACTER SET utf8 ;
USE `semAglomerar` ;

-- -----------------------------------------------------
-- Table `semAglomerar`.`Login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Login` (
  `login_id` INT NOT NULL AUTO_INCREMENT,
  `login_usuario` VARCHAR(50) NOT NULL,
  `login_senha` VARCHAR(60) NOT NULL,
  `login_tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`login_id`),
  UNIQUE INDEX `login_usuario_UNIQUE` (`login_usuario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `semAglomerar`.`Responsavel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Responsavel` (
  `resp_id` INT NOT NULL AUTO_INCREMENT,
  `resp_nome` VARCHAR(50) NOT NULL,
  `resp_cpf` VARCHAR(20) NOT NULL,
  `resp_email` VARCHAR(50) NOT NULL,
  `resp_telefone` VARCHAR(50) NULL,
  PRIMARY KEY (`resp_id`),
  UNIQUE INDEX `resp_rg_UNIQUE` (`resp_cpf` ASC),
  UNIQUE INDEX `resp_email_UNIQUE` (`resp_email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `semAglomerar`.`Shopping`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Shopping` (
  `shop_id` INT NOT NULL AUTO_INCREMENT,
  `shop_nome` VARCHAR(50) NOT NULL,
  `shop_cnpj` VARCHAR(20) NOT NULL,
  `shop_status` VARCHAR(50) NOT NULL,
  `shop_endereco` LONGTEXT NOT NULL,
  `shop_logo` VARCHAR(50) NULL,
  `shop_login_id` INT NOT NULL,
  `shop_resp_id` INT NOT NULL,
  PRIMARY KEY (`shop_id`),
  UNIQUE INDEX `shop_cnpj_UNIQUE` (`shop_cnpj` ASC),
  INDEX `fk_Shopping_Login_idx` (`shop_login_id` ASC),
  INDEX `fk_Shopping_Responsavel_idx` (`shop_resp_id` ASC),
  CONSTRAINT `fk_Shopping_Login`
    FOREIGN KEY (`shop_login_id`)
    REFERENCES `semAglomerar`.`Login` (`login_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Shopping_Responsavel`
    FOREIGN KEY (`shop_resp_id`)
    REFERENCES `semAglomerar`.`Responsavel` (`resp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `semAglomerar`.`Loja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Loja` (
  `loja_id` INT NOT NULL AUTO_INCREMENT,
  `loja_nome` VARCHAR(50) NOT NULL,
  `loja_cnpj` VARCHAR(20) NOT NULL,
  `loja_razao` VARCHAR(50) NOT NULL,
  `loja_localiza` VARCHAR(45) NOT NULL,
  `loja_categoria` VARCHAR(50) NOT NULL,    
  `loja_logo` VARCHAR(50) NULL,    
  `loja_shop_id` INT NOT NULL,
  `loja_login_id` INT NOT NULL,
  `loja_resp_id` INT NOT NULL,
  PRIMARY KEY (`loja_id`),
  UNIQUE INDEX `loja_cnpj_UNIQUE` (`loja_cnpj` ASC),
  INDEX `fk_Loja_Shopping_idx` (`loja_shop_id` ASC),
  INDEX `fk_Loja_Login_idx` (`loja_login_id` ASC),
  INDEX `fk_Loja_Responsavel_idx` (`loja_resp_id` ASC),
  CONSTRAINT `fk_Loja_Shopping`
    FOREIGN KEY (`loja_shop_id`)
    REFERENCES `semAglomerar`.`Shopping` (`shop_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Loja_Login`
    FOREIGN KEY (`loja_login_id`)
    REFERENCES `semAglomerar`.`Login` (`login_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Loja_Responsavel`
    FOREIGN KEY (`loja_resp_id`)
    REFERENCES `semAglomerar`.`Responsavel` (`resp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `semAglomerar`.`Relatorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Relatorio` (
  `relat_id` INT NOT NULL AUTO_INCREMENT,
  `relat_quant_cliente` INT NOT NULL,
  `relat_hora` TIME NOT NULL,
  `relat_data` DATE NOT NULL,
  `relat_loja_id` INT NOT NULL,
  `relat_shop_id` INT NOT NULL,
  PRIMARY KEY (`relat_id`),
  INDEX `fk_loja_relatorio_idx` (`relat_loja_id` ASC),
  INDEX `fk_Relatorio_Shopping_idx` (`relat_shop_id` ASC),
  CONSTRAINT `fk_loja_relatorio`
    FOREIGN KEY (`relat_loja_id`)
    REFERENCES `semAglomerar`.`Loja` (`loja_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Relatorio_Shopping`
    FOREIGN KEY (`relat_shop_id`)
    REFERENCES `semAglomerar`.`Shopping` (`shop_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO Login (login_usuario, login_senha,login_tipo) value("admin","$2a$10$OlgUxY2aZo7tyTYIffcW3OAGEBUGu3alalW6l7CVOYnQAjF7S2QE.","Administrador");

INSERT INTO Login (login_usuario, login_senha, login_tipo) value("Interlagos","$2a$10$gLO3KwyTrzLifQwc27KYAuVOh9idypeTE9i7EoESmrjB6SKhuM0MO","Shopping");
INSERT INTO Responsavel (resp_nome, resp_cpf, resp_email, resp_telefone) value("Barbara Dilnia", "456.486.212-10", "bar.admin@gmail.com", "11 99164-5788");
INSERT INTO Shopping ( shop_nome, shop_cnpj, shop_status, shop_endereco, shop_logo, shop_login_id, shop_resp_id) VALUES ("Interlagos","60.500.139/0001-26","Aprovado","Av. Sen. Teotônio Vilela, 261 - Interlagos, São Paulo - SP, 04801-010", "n", 2, 1);


INSERT INTO Login (login_usuario, login_senha, login_tipo) value("Livraria Saraiva","$2a$10$gLO3KwyTrzLifQwc27KYAuVOh9idypeTE9i7EoESmrjB6SKhuM0MO","Loja");
INSERT INTO Responsavel (resp_nome, resp_cpf, resp_email, resp_telefone) value("Carlos Diniz", "876.155.542-17", "carlos.diniz@gmail.com", "11 94567-5778");
INSERT INTO Loja (loja_nome,loja_cnpj,loja_razao,loja_localiza,loja_categoria,loja_logo,loja_shop_id,loja_login_id,loja_resp_id) VALUES ("Livraria Saraiva","56.563.158/0001-24","SARAIVA LIVR","Térrio, Loja 5","Livraria","",1,3,2);


INSERT INTO Login (login_usuario, login_senha, login_tipo) value("Kalunga","$2a$10$gLO3KwyTrzLifQwc27KYAuVOh9idypeTE9i7EoESmrjB6SKhuM0MO","Loja");
INSERT INTO Responsavel (resp_nome, resp_cpf, resp_email, resp_telefone) value("Claudia Alvarenga", "045.844.882-34", "c.alvarenga@gmail.com", "11 97774-4588");
INSERT INTO Loja (loja_nome,loja_cnpj,loja_razao,loja_localiza,loja_categoria,loja_logo,loja_shop_id,loja_login_id,loja_resp_id) VALUES ("Kalunga","43.283.811/0001-50","KALUNGA COMERCIO E INDUSTRIA GRAFICA LTDA","Piso 1, Loja 15","Papelaria","",1,4,3);


-- ALTERAÇÕES (2/12/2020)
ALTER TABLE Loja ADD COLUMN loja_status VARCHAR(20) DEFAULT("Ativo");